/**
 * Stage 2: GPX 1.1 generator service.
 *
 * Converts an ordered list of PipelineSegments into a valid GPX 1.1 document.
 *
 * Features:
 *  - Direction-aware: segments with reversed=true are traversed tail→head.
 *  - Discontinuity detection: if two consecutive segments are not spatially
 *    connected, a new <trkseg> element is started automatically.
 *  - Attribution: contributing source names / licenses are written into the
 *    <metadata><desc> block.
 *
 * All functions are pure and side-effect-free (no I/O).
 */

import type {
  Coordinate,
  GpxGeneratorInput,
  GpxGeneratorResult,
  PipelineSegment,
  SourceAttribution,
} from '@/lib/pipeline/types';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * Maximum distance (in degrees of WGS-84 lat/lng) between the last point of
 * one segment and the first point of the next before a new <trkseg> is opened.
 * ~0.0005° ≈ 55 m at mid-latitudes — generous enough for snapped data.
 */
const CONTINUITY_THRESHOLD_DEG = 0.0005;

const GPX_XMLNS = 'http://www.topografix.com/GPX/1/1';
const GPX_XSI = 'http://www.w3.org/2001/XMLSchema-instance';
const GPX_SCHEMA_LOC =
  'http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd';

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/** Euclidean distance in degrees between two 2D points. */
function distanceDeg(a: Coordinate, b: Coordinate): number {
  const dlng = a[0] - b[0];
  const dlat = a[1] - b[1];
  return Math.sqrt(dlng * dlng + dlat * dlat);
}

/** Escape XML special characters. */
function xmlEscape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Return the effective coordinate list for a segment, applying reversal if
 * segment.reversed === true.
 */
function effectiveCoords(segment: PipelineSegment): Coordinate[] {
  const coords = segment.coordinates;
  return segment.reversed ? [...coords].reverse() : coords;
}

// ---------------------------------------------------------------------------
// Attribution builder
// ---------------------------------------------------------------------------

function buildAttributionText(attributions: SourceAttribution[]): string {
  if (attributions.length === 0) return 'TrailReady — trail-ready.com';

  const lines = attributions.map((a) => {
    const parts = [a.name];
    if (a.url) parts.push(`(${a.url})`);
    if (a.license) parts.push(`License: ${a.license}`);
    return parts.join(' ');
  });

  return ['Data sources:', ...lines, '', 'Generated by TrailReady — trail-ready.com'].join('\n');
}

// ---------------------------------------------------------------------------
// Trackpoint builder
// ---------------------------------------------------------------------------

function buildTrkpt(coord: Coordinate): string {
  const [lng, lat, ele] = coord as [number, number, number | undefined];
  const latStr = lat.toFixed(7);
  const lonStr = lng.toFixed(7);
  const eleTag = ele !== undefined ? `\n        <ele>${ele.toFixed(2)}</ele>` : '';
  return `      <trkpt lat="${latStr}" lon="${lonStr}">${eleTag}\n      </trkpt>`;
}

// ---------------------------------------------------------------------------
// Main generator
// ---------------------------------------------------------------------------

/**
 * Generate a GPX 1.1 document from an ordered list of pipeline segments.
 *
 * @param input  Track metadata and ordered segment list.
 * @returns      GPX XML string plus statistics.
 */
export function generateGpx(input: GpxGeneratorInput): GpxGeneratorResult {
  const { name, description, segments, attributions = [] } = input;

  const isoNow = new Date().toISOString();
  const escapedName = xmlEscape(name);
  const attrText = xmlEscape(buildAttributionText(attributions));
  const descLine = description
    ? `\n      <desc>${xmlEscape(description)}</desc>`
    : '';

  // -------------------------------------------------------------------------
  // Build track segments, splitting on discontinuities
  // -------------------------------------------------------------------------

  /** Accumulator for completed <trkseg> blocks. */
  const trksegs: string[] = [];
  /** Points accumulating for the current open <trkseg>. */
  let currentPoints: string[] = [];
  /** Last coordinate of the previous segment (for continuity check). */
  let lastCoord: Coordinate | null = null;
  /** Total trackpoints emitted. */
  let totalPts = 0;

  function flushSeg(): void {
    if (currentPoints.length > 0) {
      trksegs.push(
        `    <trkseg>\n${currentPoints.join('\n')}\n    </trkseg>`,
      );
      currentPoints = [];
    }
  }

  for (const segment of segments) {
    const coords = effectiveCoords(segment);
    if (coords.length === 0) continue;

    // Check continuity with the previous segment
    if (lastCoord !== null) {
      const firstCoord = coords[0];
      const dist = distanceDeg(lastCoord, firstCoord);
      if (dist > CONTINUITY_THRESHOLD_DEG) {
        // Gap detected — close the current <trkseg> and start a new one
        flushSeg();
      }
    }

    // Append trackpoints
    for (const coord of coords) {
      currentPoints.push(buildTrkpt(coord));
      totalPts++;
    }

    lastCoord = coords[coords.length - 1];
  }

  // Flush the final segment
  flushSeg();

  // -------------------------------------------------------------------------
  // Assemble GPX document
  // -------------------------------------------------------------------------

  const trksegXml = trksegs.join('\n');

  const gpx = `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1"
     creator="TrailReady"
     xmlns="${GPX_XMLNS}"
     xmlns:xsi="${GPX_XSI}"
     xsi:schemaLocation="${GPX_SCHEMA_LOC}">
  <metadata>
    <name>${escapedName}</name>${descLine}
    <desc>${attrText}</desc>
    <author>
      <name>TrailReady</name>
      <link href="https://trail-ready.com"><text>TrailReady</text></link>
    </author>
    <time>${isoNow}</time>
  </metadata>
  <trk>
    <name>${escapedName}</name>
${trksegXml}
  </trk>
</gpx>`;

  return {
    gpx,
    trackSegmentCount: trksegs.length,
    trackpointCount: totalPts,
  };
}
